### ISSUE TITLE
Periodic test for pe-wgs-ivar-analysis failing

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/iwc#77]
This is for `pangolin --update-data --datadir datadir && pangolin --threads ${GALAXY_SLOTS:-1} --datadir 'datadir'   --outfile report.csv --max-ambig 0.5 --min-length 10000 '/tmp/tmp0w_tc3zq/files/000/dataset_34.dat' && csvtk csv2tab report.csv > '/tmp/tmp0w_tc3zq/files/000/dataset_35.dat'`:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/http/client.py", line 556, in _get_chunk_left
    chunk_left = self._read_next_chunk_size()
  File "/usr/local/lib/python3.8/http/client.py", line 523, in _read_next_chunk_size
    return int(line, 16)
ValueError: invalid literal for int() with base 16: b''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/http/client.py", line 573, in _readall_chunked
    chunk_left = self._get_chunk_left()
  File "/usr/local/lib/python3.8/http/client.py", line 558, in _get_chunk_left
    raise IncompleteRead(b'')
http.client.IncompleteRead: IncompleteRead(0 bytes read)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/pangolin", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/pangolin/command.py", line 172, in main
    update({'pangolearn': pangoLEARN.__version__,
  File "/usr/local/lib/python3.8/site-packages/pangolin/command.py", line 520, in update
    open(tarball_path, 'wb').write(request.urlopen(latest_release_tarball).read())
  File "/usr/local/lib/python3.8/http/client.py", line 466, in read
    return self._readall_chunked()
  File "/usr/local/lib/python3.8/http/client.py", line 580, in _readall_chunked
    raise IncompleteRead(b''.join(value))
http.client.IncompleteRead: IncompleteRead(80709684 bytes read)
```

Do we need to update pangolin here @wm75  ?

**Comment by mvdbeek** [comment]
Seems to work currently: https://github.com/iwc-workflows/sars-cov-2-pe-illumina-artic-ivar-analysis/actions
